-- MySQL Script generated by MySQL Workbench
-- Mon Oct 12 18:32:08 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema oficioive7122020
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `oficioive7122020` ;

-- -----------------------------------------------------
-- Schema oficioive7122020
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `oficioive7122020` DEFAULT CHARACTER SET utf8 ;
USE `oficioive7122020` ;

-- -----------------------------------------------------
-- Table `oficioive7122020`.`pais`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oficioive7122020`.`pais` ;

CREATE TABLE IF NOT EXISTS `oficioive7122020`.`pais` (
  `idPais` INT NOT NULL AUTO_INCREMENT,
  `codigoPais` VARCHAR(2) NOT NULL,
  `nombrePais` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPais`, `codigoPais`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficioive7122020`.`departamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oficioive7122020`.`departamento` ;

CREATE TABLE IF NOT EXISTS `oficioive7122020`.`departamento` (
  `idDepartamento` INT NOT NULL AUTO_INCREMENT,
  `codigoDepartamento` VARCHAR(2) NOT NULL,
  `nombreDepartamento` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`idDepartamento`, `codigoDepartamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficioive7122020`.`municipio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oficioive7122020`.`municipio` ;

CREATE TABLE IF NOT EXISTS `oficioive7122020`.`municipio` (
  `idMunicipio` INT NOT NULL AUTO_INCREMENT,
  `codigoDepartamento` INT NOT NULL,
  `codigoMunicipio` VARCHAR(4) NOT NULL,
  `nombreMunicipio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMunicipio`),
  INDEX `CODIGOMUNI` (`codigoDepartamento` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficioive7122020`.`lugar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oficioive7122020`.`lugar` ;

CREATE TABLE IF NOT EXISTS `oficioive7122020`.`lugar` (
  `idLugar` INT NOT NULL AUTO_INCREMENT,
  `pais` INT NOT NULL,
  `departamento` INT NULL,
  `municipio` INT NULL,
  PRIMARY KEY (`idLugar`),
  INDEX `fk_lugar_pais_idx` (`pais` ASC) VISIBLE,
  INDEX `fk_lugar_departamento_idx` (`departamento` ASC) VISIBLE,
  INDEX `fk_lugar_municipio_idx` (`municipio` ASC) VISIBLE,
  CONSTRAINT `fk_lugar_pais`
    FOREIGN KEY (`pais`)
    REFERENCES `oficioive7122020`.`pais` (`idPais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lugar_departamento`
    FOREIGN KEY (`departamento`)
    REFERENCES `oficioive7122020`.`departamento` (`idDepartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lugar_municipio`
    FOREIGN KEY (`municipio`)
    REFERENCES `oficioive7122020`.`municipio` (`idMunicipio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficioive7122020`.`listaCondicionMigratoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oficioive7122020`.`listaCondicionMigratoria` ;

CREATE TABLE IF NOT EXISTS `oficioive7122020`.`listaCondicionMigratoria` (
  `idListaCondicionMigratoria` INT NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idListaCondicionMigratoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficioive7122020`.`origenRiqueza`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oficioive7122020`.`origenRiqueza` ;

CREATE TABLE IF NOT EXISTS `oficioive7122020`.`origenRiqueza` (
  `idOrigenRiqueza` INT NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idOrigenRiqueza`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficioive7122020`.`datosPep`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oficioive7122020`.`datosPep` ;

CREATE TABLE IF NOT EXISTS `oficioive7122020`.`datosPep` (
  `idDatosPep` INT NOT NULL AUTO_INCREMENT,
  `entidad` VARCHAR(400) NOT NULL,
  `puestoDesempenia` VARCHAR(200) NOT NULL,
  `pais` INT NOT NULL,
  `origenRiqueza` INT NOT NULL,
  `otroOrigenRiqueza` VARCHAR(100) NULL,
  PRIMARY KEY (`idDatosPep`),
  INDEX `fk_paisEntidad_idx` (`pais` ASC) VISIBLE,
  INDEX `fk_datospep_origenRiqueza_idx` (`origenRiqueza` ASC) VISIBLE,
  CONSTRAINT `fk_datospep_paisEntidad`
    FOREIGN KEY (`pais`)
    REFERENCES `oficioive7122020`.`pais` (`idPais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_datospep_origenRiqueza`
    FOREIGN KEY (`origenRiqueza`)
    REFERENCES `oficioive7122020`.`origenRiqueza` (`idOrigenRiqueza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficioive7122020`.`parentescoPep`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oficioive7122020`.`parentescoPep` ;

CREATE TABLE IF NOT EXISTS `oficioive7122020`.`parentescoPep` (
  `idParentescoPep` INT NOT NULL AUTO_INCREMENT,
  `parentesco` VARCHAR(2) NOT NULL,
  `descripcionParentesco` VARCHAR(45) NULL,
  PRIMARY KEY (`idParentescoPep`, `parentesco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficioive7122020`.`motivoAsociacionPep`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oficioive7122020`.`motivoAsociacionPep` ;

CREATE TABLE IF NOT EXISTS `oficioive7122020`.`motivoAsociacionPep` (
  `idMotivoAsociacionPep` INT NOT NULL AUTO_INCREMENT,
  `motivoAsociacion` VARCHAR(2) NOT NULL,
  `descripcionMotivoAsociacion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMotivoAsociacionPep`, `motivoAsociacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficioive7122020`.`parienteAsociadoPep`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oficioive7122020`.`parienteAsociadoPep` ;

CREATE TABLE IF NOT EXISTS `oficioive7122020`.`parienteAsociadoPep` (
  `idParienteAsociadoPep` INT NOT NULL AUTO_INCREMENT,
  `parentesco` INT NOT NULL,
  `otroParentesco` VARCHAR(100) NULL,
  `motivoAsociacion` INT NOT NULL,
  `otroMotivoAsociacion` VARCHAR(100) NULL,
  `primerApellido` VARCHAR(15) NOT NULL,
  `segundoApellido` VARCHAR(15) NOT NULL,
  `apellidoCasada` VARCHAR(15) NULL,
  `primerNombre` VARCHAR(15) NOT NULL,
  `segundoNombre` VARCHAR(15) NOT NULL,
  `otrosNombres` VARCHAR(30) NULL,
  `sexo` VARCHAR(1) NOT NULL,
  `condificion` VARCHAR(1) NOT NULL,
  `entidad` VARCHAR(400) NOT NULL,
  `puestoDesempenia` VARCHAR(200) NOT NULL,
  `paisEntidad` INT NOT NULL,
  PRIMARY KEY (`idParienteAsociadoPep`),
  INDEX `fk_parienteAsociadoPep_ParentescoPep_idx` (`parentesco` ASC) VISIBLE,
  INDEX `fk_pap_motivoAsociacionPep_idx` (`motivoAsociacion` ASC) VISIBLE,
  INDEX `fk_paisEntidad_pais_idx` (`paisEntidad` ASC) VISIBLE,
  CONSTRAINT `fk_pap_ParentescoPep`
    FOREIGN KEY (`parentesco`)
    REFERENCES `oficioive7122020`.`parentescoPep` (`idParentescoPep`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pap_motivoAsociacionPep`
    FOREIGN KEY (`motivoAsociacion`)
    REFERENCES `oficioive7122020`.`motivoAsociacionPep` (`idMotivoAsociacionPep`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_paisEntidad_pais`
    FOREIGN KEY (`paisEntidad`)
    REFERENCES `oficioive7122020`.`pais` (`idPais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficioive7122020`.`datosPersonales`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oficioive7122020`.`datosPersonales` ;

CREATE TABLE IF NOT EXISTS `oficioive7122020`.`datosPersonales` (
  `idDatosPersonales` INT NOT NULL AUTO_INCREMENT,
  `primerApellido` VARCHAR(15) NOT NULL,
  `segundoApellido` VARCHAR(15) NOT NULL,
  `apellidoCasada` VARCHAR(15) NULL,
  `primerNombre` VARCHAR(15) NOT NULL,
  `segundoNombre` VARCHAR(15) NOT NULL,
  `otrosNombres` VARCHAR(30) NULL,
  `fechaNacimiento` DATE NOT NULL,
  `nacionalidades` INT NOT NULL,
  `nacimiento` INT NOT NULL,
  `condicionMigratoria` INT NULL,
  `otraCondicionMigratoria` VARCHAR(100) NULL,
  `sexo` VARCHAR(1) NOT NULL,
  `estadoCivil` VARCHAR(1) NOT NULL,
  `profesionOficio` VARCHAR(100) NOT NULL,
  `tipoDocumentoIdentificacion` ENUM('D', 'P') NOT NULL,
  `numeroDocumentoIdentificacion` VARCHAR(20) NOT NULL,
  `emisionPasaporte` INT NULL,
  `nit` VARCHAR(20) NOT NULL,
  `telefonos` INT NULL,
  `email` VARCHAR(100) NOT NULL,
  `direccionResidencia` VARCHAR(400) NOT NULL,
  `residencia` INT NULL,
  `pep` VARCHAR(1) NOT NULL,
  `datosPep` INT NULL,
  `parienteAsociadoPep` VARCHAR(1) NOT NULL,
  `datosParienteAsociadoPep` INT NULL,
  `cpe` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`idDatosPersonales`),
  INDEX `fk_nacimiento_lugar_idx` (`nacimiento` ASC) INVISIBLE,
  INDEX `fk_condicionMigratoria_listaCondicionMigratoria_idx` (`condicionMigratoria` ASC) VISIBLE,
  INDEX `fk_pep_datosPep_idx` (`datosPep` ASC) INVISIBLE,
  INDEX `fk_datospapep_parienteAsociadoPep_idx` (`datosParienteAsociadoPep` ASC) VISIBLE,
  INDEX `fk_residencia_lugar_idx` (`residencia` ASC) VISIBLE,
  INDEX `fk_emicionPasaporte_pais_idx` (`emisionPasaporte` ASC) VISIBLE,
  CONSTRAINT `fk_nacimiento_lugar`
    FOREIGN KEY (`nacimiento`)
    REFERENCES `oficioive7122020`.`lugar` (`idLugar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_condicionMigratoria_listaCondicionMigratoria`
    FOREIGN KEY (`condicionMigratoria`)
    REFERENCES `oficioive7122020`.`listaCondicionMigratoria` (`idListaCondicionMigratoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_datosPep_datosPep`
    FOREIGN KEY (`datosPep`)
    REFERENCES `oficioive7122020`.`datosPep` (`idDatosPep`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_datospapep_parienteAsociadoPep`
    FOREIGN KEY (`datosParienteAsociadoPep`)
    REFERENCES `oficioive7122020`.`parienteAsociadoPep` (`idParienteAsociadoPep`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_residencia_lugar`
    FOREIGN KEY (`residencia`)
    REFERENCES `oficioive7122020`.`lugar` (`idLugar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_emicionPasaporte_pais`
    FOREIGN KEY (`emisionPasaporte`)
    REFERENCES `oficioive7122020`.`pais` (`idPais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficioive7122020`.`informacionEconomicaInicial`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oficioive7122020`.`informacionEconomicaInicial` ;

CREATE TABLE IF NOT EXISTS `oficioive7122020`.`informacionEconomicaInicial` (
  `idInformacionEconomicaInicial` INT NOT NULL AUTO_INCREMENT,
  `montoIngresos` DECIMAL(14) NOT NULL,
  `propositoRC` VARCHAR(400) NOT NULL,
  PRIMARY KEY (`idInformacionEconomicaInicial`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficioive7122020`.`diccionarioFormulario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oficioive7122020`.`diccionarioFormulario` ;

CREATE TABLE IF NOT EXISTS `oficioive7122020`.`diccionarioFormulario` (
  `iddiccionarioFormulario` INT NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`iddiccionarioFormulario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficioive7122020`.`camposMinimos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oficioive7122020`.`camposMinimos` ;

CREATE TABLE IF NOT EXISTS `oficioive7122020`.`camposMinimos` (
  `idCamposMinimos` INT NOT NULL AUTO_INCREMENT,
  `tipoActuacion` ENUM('C', 'R') NOT NULL,
  `calidadActua` VARCHAR(100) NULL,
  `lugar` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `cliente` INT NOT NULL,
  `representante` INT NULL,
  `infoEconomica` INT NOT NULL,
  `diccionarioFormulario` INT NULL,
  PRIMARY KEY (`idCamposMinimos`),
  INDEX `fk_actclie_lugar_idx` (`lugar` ASC) VISIBLE,
  INDEX `fk_actclie_cliente_datosPersonales_idx` (`cliente` ASC) VISIBLE,
  INDEX `fk_actclie_representante_datosPersonales_idx` (`representante` ASC) VISIBLE,
  INDEX `fk_actclie_infoEcoIni_idx` (`infoEconomica` ASC) VISIBLE,
  INDEX `fk_cm_dicFm_idx` (`diccionarioFormulario` ASC) VISIBLE,
  CONSTRAINT `fk_actclie_lugar`
    FOREIGN KEY (`lugar`)
    REFERENCES `oficioive7122020`.`lugar` (`idLugar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_actclie_cliente_datosPersonales`
    FOREIGN KEY (`cliente`)
    REFERENCES `oficioive7122020`.`datosPersonales` (`idDatosPersonales`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_actclie_representante_datosPersonales`
    FOREIGN KEY (`representante`)
    REFERENCES `oficioive7122020`.`datosPersonales` (`idDatosPersonales`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_actclie_infoEcoIni`
    FOREIGN KEY (`infoEconomica`)
    REFERENCES `oficioive7122020`.`informacionEconomicaInicial` (`idInformacionEconomicaInicial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cm_dicFm`
    FOREIGN KEY (`diccionarioFormulario`)
    REFERENCES `oficioive7122020`.`diccionarioFormulario` (`iddiccionarioFormulario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficioive7122020`.`productoServicio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oficioive7122020`.`productoServicio` ;

CREATE TABLE IF NOT EXISTS `oficioive7122020`.`productoServicio` (
  `idProductoServicio` INT NOT NULL AUTO_INCREMENT,
  `lugarProducto` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `tipoProducto` VARCHAR(100) NOT NULL,
  `nombreProducto` VARCHAR(300) NOT NULL,
  `descripcionProducto` VARCHAR(600) NOT NULL,
  `identificadorProducto` VARCHAR(50) NULL,
  `nombreContrataProducto` VARCHAR(400) NOT NULL,
  `moneda` VARCHAR(3) NOT NULL,
  `valor` DECIMAL(14) NOT NULL,
  `otrosFirmantes` INT NULL,
  PRIMARY KEY (`idProductoServicio`),
  INDEX `fk_ps_lugar_idx` (`lugarProducto` ASC) VISIBLE,
  CONSTRAINT `fk_ps_lugar`
    FOREIGN KEY (`lugarProducto`)
    REFERENCES `oficioive7122020`.`lugar` (`idLugar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficioive7122020`.`fuenteIngresos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oficioive7122020`.`fuenteIngresos` ;

CREATE TABLE IF NOT EXISTS `oficioive7122020`.`fuenteIngresos` (
  `idFuenteIngresos` INT NOT NULL AUTO_INCREMENT,
  `idInformacionEconomicaInicial` INT NOT NULL,
  `tipo` VARCHAR(2) NOT NULL,
  `nombreComercialOtrasFuentes` VARCHAR(400) NULL,
  `nombreEmpleador` VARCHAR(200) NULL,
  PRIMARY KEY (`idFuenteIngresos`),
  INDEX `fk_infoEcoIni_fuenteIngresos_idx` (`idInformacionEconomicaInicial` ASC) VISIBLE,
  CONSTRAINT `fk_infoEcoIni_fuenteIngresos`
    FOREIGN KEY (`idInformacionEconomicaInicial`)
    REFERENCES `oficioive7122020`.`informacionEconomicaInicial` (`idInformacionEconomicaInicial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficioive7122020`.`camposMinimosFirmante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oficioive7122020`.`camposMinimosFirmante` ;

CREATE TABLE IF NOT EXISTS `oficioive7122020`.`camposMinimosFirmante` (
  `idCamposMinimosFirmante` INT NOT NULL AUTO_INCREMENT,
  `tipoActuacion` VARCHAR(1) NOT NULL,
  `calidadActua` VARCHAR(100) NULL,
  `lugar` INT NOT NULL,
  `fecha` DATE NULL,
  `firmante` INT NULL,
  `representante` INT NULL,
  PRIMARY KEY (`idCamposMinimosFirmante`),
  INDEX `fk_camposMinimosFirmante_lugar_idx` (`lugar` ASC) VISIBLE,
  INDEX `fk_camposMinimos_datosPersonales_idx` (`firmante` ASC) VISIBLE,
  CONSTRAINT `fk_camposMinimosFirmante_lugar`
    FOREIGN KEY (`lugar`)
    REFERENCES `oficioive7122020`.`lugar` (`idLugar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_camposMinimos_datosPersonales`
    FOREIGN KEY (`firmante`)
    REFERENCES `oficioive7122020`.`datosPersonales` (`idDatosPersonales`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `oficioive7122020`.`pais`
-- -----------------------------------------------------
START TRANSACTION;
USE `oficioive7122020`;
INSERT INTO `oficioive7122020`.`pais` (`idPais`, `codigoPais`, `nombrePais`) VALUES (1, 'GT', 'GUATEMALA');
INSERT INTO `oficioive7122020`.`pais` (`idPais`, `codigoPais`, `nombrePais`) VALUES (2, 'AG', 'AFGANISTÁN');

COMMIT;


-- -----------------------------------------------------
-- Data for table `oficioive7122020`.`departamento`
-- -----------------------------------------------------
START TRANSACTION;
USE `oficioive7122020`;
INSERT INTO `oficioive7122020`.`departamento` (`idDepartamento`, `codigoDepartamento`, `nombreDepartamento`) VALUES (1, '01', 'GUATEMALA');
INSERT INTO `oficioive7122020`.`departamento` (`idDepartamento`, `codigoDepartamento`, `nombreDepartamento`) VALUES (2, '02', 'SACATEPÉQUEZ');
INSERT INTO `oficioive7122020`.`departamento` (`idDepartamento`, `codigoDepartamento`, `nombreDepartamento`) VALUES (3, '03', 'CHIMALTENANGO');
INSERT INTO `oficioive7122020`.`departamento` (`idDepartamento`, `codigoDepartamento`, `nombreDepartamento`) VALUES (4, '04', 'EL PROGRESO');
INSERT INTO `oficioive7122020`.`departamento` (`idDepartamento`, `codigoDepartamento`, `nombreDepartamento`) VALUES (5, '05', 'ESCUINTLA');
INSERT INTO `oficioive7122020`.`departamento` (`idDepartamento`, `codigoDepartamento`, `nombreDepartamento`) VALUES (6, '06', 'SANTA ROSA');
INSERT INTO `oficioive7122020`.`departamento` (`idDepartamento`, `codigoDepartamento`, `nombreDepartamento`) VALUES (7, '07', ' SOLOLÁ');
INSERT INTO `oficioive7122020`.`departamento` (`idDepartamento`, `codigoDepartamento`, `nombreDepartamento`) VALUES (8, '08', ' TOTONICAPÁN');
INSERT INTO `oficioive7122020`.`departamento` (`idDepartamento`, `codigoDepartamento`, `nombreDepartamento`) VALUES (9, '09', ' QUETZALTENANGO');
INSERT INTO `oficioive7122020`.`departamento` (`idDepartamento`, `codigoDepartamento`, `nombreDepartamento`) VALUES (10, '10', ' SUCHITEPÉQUEZ');
INSERT INTO `oficioive7122020`.`departamento` (`idDepartamento`, `codigoDepartamento`, `nombreDepartamento`) VALUES (11, '11', ' RETALHULEU');
INSERT INTO `oficioive7122020`.`departamento` (`idDepartamento`, `codigoDepartamento`, `nombreDepartamento`) VALUES (12, '12', ' SAN MARCOS');
INSERT INTO `oficioive7122020`.`departamento` (`idDepartamento`, `codigoDepartamento`, `nombreDepartamento`) VALUES (13, '13', ' HUEHUETENANGO');
INSERT INTO `oficioive7122020`.`departamento` (`idDepartamento`, `codigoDepartamento`, `nombreDepartamento`) VALUES (14, '14', ' EL QUICHÉ');
INSERT INTO `oficioive7122020`.`departamento` (`idDepartamento`, `codigoDepartamento`, `nombreDepartamento`) VALUES (15, '15', ' BAJA VERAPAZ');
INSERT INTO `oficioive7122020`.`departamento` (`idDepartamento`, `codigoDepartamento`, `nombreDepartamento`) VALUES (16, '16', ' ALTA VERAPAZ');
INSERT INTO `oficioive7122020`.`departamento` (`idDepartamento`, `codigoDepartamento`, `nombreDepartamento`) VALUES (17, '17', ' PETÉN');
INSERT INTO `oficioive7122020`.`departamento` (`idDepartamento`, `codigoDepartamento`, `nombreDepartamento`) VALUES (18, '18', ' IZABAL');
INSERT INTO `oficioive7122020`.`departamento` (`idDepartamento`, `codigoDepartamento`, `nombreDepartamento`) VALUES (19, '19', ' ZACAPA');
INSERT INTO `oficioive7122020`.`departamento` (`idDepartamento`, `codigoDepartamento`, `nombreDepartamento`) VALUES (20, '20', ' CHIQUIMULA');
INSERT INTO `oficioive7122020`.`departamento` (`idDepartamento`, `codigoDepartamento`, `nombreDepartamento`) VALUES (21, '21', ' JALAPA');
INSERT INTO `oficioive7122020`.`departamento` (`idDepartamento`, `codigoDepartamento`, `nombreDepartamento`) VALUES (22, '22', ' JUTIAPA');

COMMIT;


-- -----------------------------------------------------
-- Data for table `oficioive7122020`.`municipio`
-- -----------------------------------------------------
START TRANSACTION;
USE `oficioive7122020`;
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (1, 1, '0101', 'GUATEMALA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (2, 1, '0102', 'SANTA CATARINA PINULA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (3, 01, '0103', 'SAN JOSÉ PINULA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (4, 01, '0104', 'SAN JOSÉ DEL GOLFO');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (5, 01, '0105', 'PALENCIA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (6, 01, '0106', 'CHINAUTLA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (7, 01, '0107', 'SAN PEDRO AYAMPUC');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (8, 01, '0108', 'MIXCO');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (9, 01, '0109', 'SAN PEDRO SACATEPÉQUEZ');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (10, 01, '0110', 'SAN JUAN SACATEPÉQUEZ');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (11, 01, '0111', 'SAN RAYMUNDO');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (12, 01, '0112', 'CHUARRANCHO');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (13, 01, '0113', 'FRAIJANES');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (14, 01, '0114', 'AMATITLÁN');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (15, 01, '0115', 'VILLA NUEVA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (16, 01, '0116', 'VILLA CANALES');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (17, 01, '0117', 'SAN MIGUEL PETAPA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (18, 04, '0201', 'GUASTATOYA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (19, 04, '0202', 'MORAZÁN');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (20, 04, '0203', 'SAN AGUSTÍN ACASAGUASTLÁN');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (21, 04, '0204', 'SAN CRISTÓBAL ACASAGUASTLÁN');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (22, 04, '0205', 'EL JÍCARO');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (23, 04, '0206', 'SANSARE');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (24, 04, '0207', 'SANARATE');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (25, 04, '0208', 'SAN ANTONIO LA PAZ');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (26, 02, '0301', 'ANTIGUA GUATEMALA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (27, 02, '0302', 'JOCOTENANGO');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (28, 02, '0303', 'PASTORES');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (29, 02, '0304', 'SUMPANGO');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (30, 02, '0305', 'SANTO DOMINGO XENACOJ');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (31, 02, '0306', 'SANTIAGO SACATEPEQUÉZ');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (32, 02, '0307', 'SAN BARTOLOMÉ MILPAS ALTAS');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (33, 02, '0308', 'SAN LUCAS SACATEPÉQUEZ');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (34, 02, '0309', 'SANTA LUCÍA MILPAS ALTAS');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (35, 02, '0310', 'MAGDALENA MILPAS ALTAS');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (36, 02, '0311', 'SANTA MARÍA DE JESÚS');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (37, 02, '0312', 'CIUDAD VIEJA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (38, 02, '0313', 'SAN MIGUEL DUEÑAS');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (39, 02, '0314', 'ALOTENANGO');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (40, 02, '0315', 'SAN ANTONIO AGUAS CALIENTES');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (41, 02, '0316', 'SANTA CATARINA BARAHONA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (42, 03, '0401', 'CHIMALTENANGO');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (43, 03, '0402', 'SAN JOSÉ POAQUIL');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (44, 03, '0403', 'SAN MARTÍN JILOTEPEQUE');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (45, 03, '0404', 'SAN JUAN COMALAPA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (46, 03, '0405', 'SANTA APOLONIA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (47, 03, '0406', 'TECPÁN GUATEMALA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (48, 03, '0407', 'PATZÚN');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (49, 03, '0408', 'POCHUTA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (50, 03, '0409', 'PATZICÍA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (51, 03, '0410', 'SANTA CRUZ BALANYA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (52, 03, '0411', 'ACATENANGO');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (53, 03, '0412', 'SAN PEDRO YEPOCAPA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (54, 03, '0413', 'SAN ANDRÉS ITZAPA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (55, 03, '0414', 'PARRAMOS');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (56, 03, '0415', 'ZARAGOZA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (57, 03, '0416', 'EL TEJAR');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (58, 05, '0501', 'ESCUINTLA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (59, 05, '0502', 'SANTA LUCÍA COTZUMALGUAPA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (60, 05, '0503', 'LA DEMOCRACIA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (61, 05, '0504', 'SIQUINALÁ');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (62, 05, '0505', 'MASAGUA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (63, 05, '0506', 'TIQUISATE');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (64, 05, '0507', 'LA GOMERA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (65, 05, '0508', 'GUANAGAZAPA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (66, 05, '0509', 'PUERTO SAN JOSÉ');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (67, 05, '0510', 'IZTAPA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (68, 05, '0511', 'PALÍN');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (69, 05, '0512', 'SAN VICENTE PACAYA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (70, 05, '0513', 'NUEVA CONCEPCIÓN');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (71, 05, '0514', 'SIPACATE');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (72, 06, '0601', 'CUILAPA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (73, 06, '0602', 'BARBERENA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (74, 06, '0603', 'SANTA ROSA DE LIMA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (75, 06, '0604', 'CASILLAS');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (76, 06, '0605', 'SAN RAFAEL LAS FLORES');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (77, 06, '0606', 'ORATORIO');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (78, 06, '0607', 'SAN JUAN TECUACO');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (79, 06, '0608', 'CHIQUIMULILLA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (80, 06, '0609', 'TAXISCO');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (81, 06, '0610', 'SANTA MARÍA IXHUATÁN');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (82, 06, '0611', 'GUAZACAPÁN');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (83, 06, '0612', 'SANTA CRUZ NARANJO');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (84, 06, '0613', 'PUEBLO NUEVO VIÑAS');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (85, 06, '0614', 'NUEVA SANTA ROSA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (86, 07, '0701', 'SOLOLÁ');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (87, 07, '0702', 'SAN JOSÉ CHACAYÁ');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (88, 07, '0703', 'SANTA MARÍA VISITACIÓN');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (89, 07, '0704', 'SANTA LUCÍA UTATLÁN');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (90, 07, '0705', 'NAHUALÁ');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (91, 07, '0706', 'SANTA CATARINA IXTAHUACÁN');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (92, 07, '0707', 'SANTA CLARA LA LAGUNA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (93, 07, '0708', 'CONCEPCIÓN');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (94, 07, '0709', 'SAN ANDRÉS SEMETABAJ');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (95, 07, '0710', 'PANAJACHEL');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (96, 07, '0711', 'SANTA CATARINA PALOPÓ');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (97, 07, '0712', 'SAN ANTONIO PALOPÓ');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (98, 07, '0713', 'SAN LUCAS TOLIMÁN');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (99, 07, '0714', 'SANTA CRUZ LA LAGUNA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (100, 07, '0715', 'SAN PABLO LA LAGUNA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (101, 07, '0716', 'SAN MARCOS LA LAGUNA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (102, 07, '0717', 'SAN JUAN LA LAGUNA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (103, 07, '0718', 'SAN PEDRO LA LAGUNA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (104, 07, '0719', 'SANTIAGO ATITLÁN');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (105, 08, '0801', 'TOTONICAPÁN');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (106, 08, '0802', 'SAN CRISTÓBAL TOTONICAPÁN');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (107, 08, '0803', 'SAN FRANCISCO EL ALTO');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (108, 08, '0804', 'SAN ANDRÉS XECUL');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (109, 08, '0805', 'MOMOSTENANGO');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (110, 08, '0806', 'SANTA MARÍA CHIQUIMULA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (111, 08, '0807', 'SANTA LUCÍA LA REFORMA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (112, 08, '0808', 'SAN BARTOLO');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (113, 09, '0901', 'QUETZALTENANGO');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (114, 09, '0902', 'SALCAJÁ');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (115, 09, '0903', 'OLINTEPEQUE');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (116, 09, '0904', 'SAN CARLOS SIJA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (117, 09, '0905', 'SIBILIA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (118, 09, '0906', 'CABRICÁN');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (119, 09, '0907', 'CAJOLA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (120, 09, '0908', 'SAN MIGUEL SIGUILA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (121, 09, '0909', 'SAN JUAN OSTUNCALCO');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (122, 09, '0910', 'SAN MATEO');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (123, 09, '0911', 'CONCEPCIÓN CHIQUIRICHAPA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (124, 09, '0912', 'SAN MARTÍN SACATEPÉQUEZ');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (125, 09, '0913', 'ALMOLONGA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (126, 09, '0914', 'CANTEL');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (127, 09, '0915', 'HUITÁN');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (128, 09, '0916', 'ZUNIL');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (129, 09, '0917', 'COLOMBA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (130, 09, '0918', 'SAN FRANCISCO LA UNIÓN');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (131, 09, '0919', 'EL PALMAR');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (132, 09, '0920', 'COATEPEQUE');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (133, 09, '0921', 'GÉNOVA COSTA CUCA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (134, 09, '0922', 'FLORES');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (135, 09, '0923', 'LA ESPERANZA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (136, 09, '0924', 'PALESTINA DE LOS ALTOS');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (137, 10, '1001', 'MAZATENANGO');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (138, 10, '1002', 'CUYOTENANGO');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (139, 10, '1003', 'SAN FRANCISCO ZAPOTITLÁN');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (140, 10, '1004', 'SAN BERNARDINO');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (141, 10, '1005', 'SAN JOSÉ EL ÍDOLO');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (142, 10, '1006', 'SANTO DOMINGO SUCHITEPEQUEZ');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (143, 10, '1007', 'SAN LORENZO');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (144, 10, '1008', 'SAMAYAC');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (145, 10, '1009', 'SAN PABLO JOCOPILAS');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (146, 10, '1010', 'SAN ANTONIO SUCHITEPÉQUEZ');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (147, 10, '1011', 'SAN MIGUEL PANÁN');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (148, 10, '1012', 'SAN GABRIEL');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (149, 10, '1013', 'CHICACAO');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (150, 10, '1014', 'PATULUL');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (151, 10, '1015', 'SANTA BÁRBARA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (152, 10, '1016', 'SAN JUAN BAUTISTA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (153, 10, '1017', 'SANTO TOMÁS LA UNIÓN');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (154, 10, '1018', 'ZUNILITO');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (155, 10, '1019', 'PUEBLO NUEVO');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (156, 10, '1020', 'RÍO BRAVO');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (157, 10, '1021', 'SAN JOSÉ LA MÁQUINA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (158, 11, '1101', 'RETALHULEU');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (159, 11, '1102', 'SAN SEBASTIÁN');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (160, 11, '1103', 'SANTA CRUZ MULUÁ');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (161, 11, '1104', 'SAN MARTÍN ZAPOTITLÁN');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (162, 11, '1105', 'SAN FELIPE');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (163, 11, '1106', 'SAN ANDRÉS VILLA SECA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (164, 11, '1107', 'CHAMPERICO');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (165, 11, '1108', 'NUEVO SAN CARLOS');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (166, 11, '1109', 'EL ASINTAL');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (167, 12, '1201', 'SAN MARCOS');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (168, 12, '1202', 'SAN PEDRO SACATEPÉQUEZ');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (169, 12, '1203', 'SAN ANTONIO SACATEPÉQUEZ');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (170, 12, '1204', 'COMITANCILLO');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (171, 12, '1205', 'SAN MIGUEL IXTAHUACÁN');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (172, 12, '1206', 'CONCEPCIÓN TUTUAPA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (173, 12, '1207', 'TACANÁ');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (174, 12, '1208', 'SIBINAL');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (175, 12, '1209', 'TAJUMULCO');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (176, 12, '1210', 'TEJUTLA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (177, 12, '1211', 'SAN RAFAEL PIE DE LA CUESTA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (178, 12, '1212', 'NUEVO PROGRESO');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (179, 12, '1213', 'EL TUMBADOR');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (180, 12, '1214', 'SAN JOSE EL RODEO');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (181, 12, '1215', 'MALACATÁN');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (182, 12, '1216', 'CATARINA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (183, 12, '1217', 'AYUTLA (TECUN UMAN)');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (184, 12, '1217', 'CIUDAD TECÚN UMÁN');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (185, 12, '1218', 'OCÓS');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (186, 12, '1219', 'SAN PABLO');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (187, 12, '1220', 'EL QUETZAL');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (188, 12, '1221', 'LA REFORMA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (189, 12, '1222', 'PAJAPITA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (190, 12, '1223', 'IXCHIGUÁN');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (191, 12, '1224', 'SAN JOSÉ OJETENAM');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (192, 12, '1225', 'SAN CRISTÓBAL CUCHO');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (193, 12, '1226', 'SIPACAPA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (194, 12, '1227', 'ESQUIPULAS PALO GORDO');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (195, 12, '1228', 'RÍO BLANCO');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (196, 12, '1229', 'SAN LORENZO');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (197, 12, '1230', 'LA BLANCA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (198, 13, '1301', 'HUEHUETENANGO');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (199, 13, '1302', 'CHIANTLA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (200, 13, '1303', 'MALACATANCITO');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (201, 13, '1304', 'CUILCO');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (202, 13, '1305', 'NENTÓN');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (203, 13, '1306', 'SAN PEDRO NECTA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (204, 13, '1307', 'JACALTENANGO');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (205, 13, '1308', 'SOLOMA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (206, 13, '1309', 'IXTAHUACÁN');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (207, 13, '1310', 'SANTA BÁRBARA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (208, 13, '1311', 'LA LIBERTAD');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (209, 13, '1312', 'LA DEMOCRACIA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (210, 13, '1313', 'SAN MIGUEL ACATÁN');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (211, 13, '1314', 'SAN RAFAEL LA INDEPENDENCIA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (212, 13, '1315', 'TODOS SANTOS CUCHUMATÁN');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (213, 13, '1316', 'SAN JUAN ATITÁN');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (214, 13, '1317', 'SANTA EULALIA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (215, 13, '1318', 'SAN MATEO IXTATÁN');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (216, 13, '1319', 'COLOTENANGO');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (217, 13, '1320', 'SAN SEBASTIÁN HUEHUETENANGO');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (218, 13, '1321', 'TECTITÁN');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (219, 13, '1322', 'CONCEPCIÓN HUISTA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (220, 13, '1323', 'SAN JUAN IXCOY');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (221, 13, '1324', 'SAN ANTONIO HUISTA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (222, 13, '1325', 'SAN SEBASTIÁN COATÁN');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (223, 13, '1326', 'BARILLAS');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (224, 13, '1327', 'AGUACATÁN');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (225, 13, '1328', 'SAN RAFAEL PETZAL');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (226, 13, '1329', 'SAN GASPAR IXCHIL');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (227, 13, '1330', 'SANTIAGO CHIMALTENANGO');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (228, 13, '1331', 'SANTA ANA HUISTA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (229, 13, '1332', 'UNION CANTINIL');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (230, 13, '1333', 'PETATÁN');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (231, 14, '1401', 'SANTA CRUZ DEL QUICHÉ');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (232, 14, '1402', 'CHICHÉ');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (233, 14, '1403', 'CHINIQUE');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (234, 14, '1404', 'ZACUALPA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (235, 14, '1405', 'CHAJUL');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (236, 14, '1406', 'CHICHICASTENANGO');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (237, 14, '1407', 'PATZITE');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (238, 14, '1408', 'SAN ANTONIO ILOTENANGO');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (239, 14, '1409', 'SAN PEDRO JOCOPILAS');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (240, 14, '1410', 'CUNÉN');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (241, 14, '1411', 'SAN JUAN COTZAL');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (242, 14, '1412', 'JOYABAJ');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (243, 14, '1413', 'NEBAJ');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (244, 14, '1414', 'SAN ANDRÉS SAJCABAJA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (245, 14, '1415', 'SAN MIGUEL USPANTÁN');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (246, 14, '1416', 'SACAPULAS');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (247, 14, '1417', 'SAN BARTOLOMÉ JOCOTENANGO');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (248, 14, '1418', 'CANILLÁ');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (249, 14, '1419', 'CHICAMÁN');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (250, 14, '1420', 'IXCÁN');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (251, 14, '1421', 'PACHALUM');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (252, 15, '1501', 'SALAMÁ');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (253, 15, '1502', 'SAN MIGUEL CHICAJ');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (254, 15, '1503', 'RABINAL');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (255, 15, '1504', 'CUBULCO');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (256, 15, '1505', 'GRANADOS');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (257, 15, '1506', 'EL CHOL');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (258, 15, '1507', 'SAN JERÓNIMO');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (259, 15, '1508', 'PURULHÁ');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (260, 16, '1601', 'COBÁN');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (261, 16, '1602', 'SANTA CRUZ VERAPAZ');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (262, 16, '1603', 'SAN CRISTÓBAL VERAPAZ');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (263, 16, '1604', 'TACTIC');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (264, 16, '1605', 'TAMAHÚ');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (265, 16, '1606', 'TUCURÚ');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (266, 16, '1607', 'PANZÓS');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (267, 16, '1608', 'SENAHÚ');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (268, 16, '1609', 'SAN PEDRO CARCHÁ');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (269, 16, '1610', 'SAN JUAN CHAMELCO');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (270, 16, '1611', 'LANQUÍN');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (271, 16, '1612', 'CAHABÓN');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (272, 16, '1613', 'CHISEC');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (273, 16, '1614', 'CHAHAL');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (274, 16, '1615', 'FRAY BARTOLOMÉ DE LAS CASAS');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (275, 16, '1616', 'SANTA CATARINA LA TINTA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (276, 16, '1617', 'RAXRUHA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (277, 17, '1701', 'FLORES');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (278, 17, '1701', 'SANTA ELENA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (279, 17, '1702', 'SAN JOSÉ');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (280, 17, '1703', 'SAN BENITO');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (281, 17, '1704', 'SAN ANDRÉS');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (282, 17, '1705', 'LA LIBERTAD');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (283, 17, '1706', 'SAN FRANCISCO');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (284, 17, '1707', 'SANTA ANA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (285, 17, '1708', 'DOLORES');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (286, 17, '1709', 'SAN LUIS');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (287, 17, '1710', 'SAYAXCHÉ');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (288, 17, '1711', 'MELCHOR DE MENCOS');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (289, 17, '1712', 'POPTÚN');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (290, 17, '1713', 'LAS CRUCES');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (291, 17, '1714', 'EL CHAL');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (292, 18, '1801', 'PUERTO BARRIOS');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (293, 18, '1802', 'LIVINGSTON');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (294, 18, '1803', 'EL ESTOR');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (295, 18, '1804', 'MORALES');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (296, 18, '1805', 'LOS AMATES');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (297, 19, '1901', 'ZACAPA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (298, 19, '1902', 'ESTANZUELA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (299, 19, '1903', 'RÍO HONDO');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (300, 19, '1904', 'GUALÁN');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (301, 19, '1905', 'TECULUTÁN');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (302, 19, '1906', 'USUMATLÁN');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (303, 19, '1907', 'CABAÑAS');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (304, 19, '1908', 'SAN DIEGO');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (305, 19, '1909', 'LA UNIÓN');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (306, 19, '1910', 'HUITÉ');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (307, 19, '1911', 'SAN JORGE');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (308, 20, '2001', 'CHIQUIMULA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (309, 20, '2002', 'SAN JOSÉ LA ARADA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (310, 20, '2003', 'SAN JUAN ERMITA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (311, 20, '2004', 'JOCOTÁN');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (312, 20, '2005', 'CAMOTÁN');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (313, 20, '2006', 'OLOPA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (314, 20, '2007', 'ESQUIPULAS');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (315, 20, '2008', 'CONCEPCIÓN LAS MINAS');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (316, 20, '2009', 'QUETZALTEPEQUE');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (317, 20, '2010', 'SAN JACINTO');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (318, 20, '2011', 'IPALA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (319, 21, '2101', 'JALAPA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (320, 21, '2102', 'SAN PEDRO PINULA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (321, 21, '2103', 'SAN LUIS JILOTEPEQUE');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (322, 21, '2104', 'SAN MIGUEL CHAPARRÓN');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (323, 21, '2105', 'SAN CARLOS ALZATATE');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (324, 21, '2106', 'MONJAS');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (325, 21, '2107', 'MATAQUESCUINTLA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (326, 22, '2201', 'JUTIAPA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (327, 22, '2202', 'EL PROGRESO');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (328, 22, '2203', 'SANTA CATARINA MITA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (329, 22, '2204', 'AGUA BLANCA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (330, 22, '2205', 'ASUNCIÓN MITA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (331, 22, '2206', 'YUPILTEPEQUE');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (332, 22, '2207', 'ATESCATEMPA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (333, 22, '2208', 'JEREZ');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (334, 22, '2209', 'EL ADELANTO');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (335, 22, '2210', 'ZAPOTITLÁN');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (336, 22, '2211', 'COMAPA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (337, 22, '2212', 'JALPATAGUA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (338, 22, '2213', 'CONGUACO');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (339, 22, '2214', 'MOYUTA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (340, 22, '2215', 'PASACO');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (341, 22, '2216', 'SAN JOSÉ ACATEMPA');
INSERT INTO `oficioive7122020`.`municipio` (`idMunicipio`, `codigoDepartamento`, `codigoMunicipio`, `nombreMunicipio`) VALUES (342, 22, '2217', 'QUEZADA');

COMMIT;


-- -----------------------------------------------------
-- Data for table `oficioive7122020`.`listaCondicionMigratoria`
-- -----------------------------------------------------
START TRANSACTION;
USE `oficioive7122020`;
INSERT INTO `oficioive7122020`.`listaCondicionMigratoria` (`idListaCondicionMigratoria`, `descripcion`) VALUES (1, 'Residente temporal ');
INSERT INTO `oficioive7122020`.`listaCondicionMigratoria` (`idListaCondicionMigratoria`, `descripcion`) VALUES (2, 'Residente Permanente');
INSERT INTO `oficioive7122020`.`listaCondicionMigratoria` (`idListaCondicionMigratoria`, `descripcion`) VALUES (3, 'Turista o visitante');
INSERT INTO `oficioive7122020`.`listaCondicionMigratoria` (`idListaCondicionMigratoria`, `descripcion`) VALUES (4, 'Permiso de trabajo ');
INSERT INTO `oficioive7122020`.`listaCondicionMigratoria` (`idListaCondicionMigratoria`, `descripcion`) VALUES (5, 'Persona en tránsito');
INSERT INTO `oficioive7122020`.`listaCondicionMigratoria` (`idListaCondicionMigratoria`, `descripcion`) VALUES (6, 'Permiso consular o similar');
INSERT INTO `oficioive7122020`.`listaCondicionMigratoria` (`idListaCondicionMigratoria`, `descripcion`) VALUES (7, 'Nacionalizado/naturalizado en Guatemala');
INSERT INTO `oficioive7122020`.`listaCondicionMigratoria` (`idListaCondicionMigratoria`, `descripcion`) VALUES (8, 'Otra');

COMMIT;


-- -----------------------------------------------------
-- Data for table `oficioive7122020`.`origenRiqueza`
-- -----------------------------------------------------
START TRANSACTION;
USE `oficioive7122020`;
INSERT INTO `oficioive7122020`.`origenRiqueza` (`idOrigenRiqueza`, `descripcion`) VALUES (1, 'Bienes muebles e inmuebles por herencia');
INSERT INTO `oficioive7122020`.`origenRiqueza` (`idOrigenRiqueza`, `descripcion`) VALUES (2, 'Bienes muebles e inmuebles');
INSERT INTO `oficioive7122020`.`origenRiqueza` (`idOrigenRiqueza`, `descripcion`) VALUES (3, 'Negocio propio');
INSERT INTO `oficioive7122020`.`origenRiqueza` (`idOrigenRiqueza`, `descripcion`) VALUES (4, 'Servicios profesionales');
INSERT INTO `oficioive7122020`.`origenRiqueza` (`idOrigenRiqueza`, `descripcion`) VALUES (5, 'Préstamos bancarios');
INSERT INTO `oficioive7122020`.`origenRiqueza` (`idOrigenRiqueza`, `descripcion`) VALUES (6, 'Trabajos anteriores');
INSERT INTO `oficioive7122020`.`origenRiqueza` (`idOrigenRiqueza`, `descripcion`) VALUES (7, 'Trabajo actual');
INSERT INTO `oficioive7122020`.`origenRiqueza` (`idOrigenRiqueza`, `descripcion`) VALUES (8, 'otro');

COMMIT;


-- -----------------------------------------------------
-- Data for table `oficioive7122020`.`parentescoPep`
-- -----------------------------------------------------
START TRANSACTION;
USE `oficioive7122020`;
INSERT INTO `oficioive7122020`.`parentescoPep` (`idParentescoPep`, `parentesco`, `descripcionParentesco`) VALUES (1, 'P', 'Padre');
INSERT INTO `oficioive7122020`.`parentescoPep` (`idParentescoPep`, `parentesco`, `descripcionParentesco`) VALUES (2, 'M', 'Madre');
INSERT INTO `oficioive7122020`.`parentescoPep` (`idParentescoPep`, `parentesco`, `descripcionParentesco`) VALUES (3, 'HJ', 'Hijo');
INSERT INTO `oficioive7122020`.`parentescoPep` (`idParentescoPep`, `parentesco`, `descripcionParentesco`) VALUES (4, 'HN', 'Hermano');
INSERT INTO `oficioive7122020`.`parentescoPep` (`idParentescoPep`, `parentesco`, `descripcionParentesco`) VALUES (5, 'C', 'Cónyuge');
INSERT INTO `oficioive7122020`.`parentescoPep` (`idParentescoPep`, `parentesco`, `descripcionParentesco`) VALUES (6, 'O', 'Otro');

COMMIT;


-- -----------------------------------------------------
-- Data for table `oficioive7122020`.`motivoAsociacionPep`
-- -----------------------------------------------------
START TRANSACTION;
USE `oficioive7122020`;
INSERT INTO `oficioive7122020`.`motivoAsociacionPep` (`idMotivoAsociacionPep`, `motivoAsociacion`, `descripcionMotivoAsociacion`) VALUES (1, 'PR', 'Profesionales');
INSERT INTO `oficioive7122020`.`motivoAsociacionPep` (`idMotivoAsociacionPep`, `motivoAsociacion`, `descripcionMotivoAsociacion`) VALUES (2, 'PL', 'Políticos');
INSERT INTO `oficioive7122020`.`motivoAsociacionPep` (`idMotivoAsociacionPep`, `motivoAsociacion`, `descripcionMotivoAsociacion`) VALUES (3, 'C', 'Comerciales');
INSERT INTO `oficioive7122020`.`motivoAsociacionPep` (`idMotivoAsociacionPep`, `motivoAsociacion`, `descripcionMotivoAsociacion`) VALUES (4, 'N', 'Negocios');
INSERT INTO `oficioive7122020`.`motivoAsociacionPep` (`idMotivoAsociacionPep`, `motivoAsociacion`, `descripcionMotivoAsociacion`) VALUES (5, 'O', 'Otros');

COMMIT;

