-- MySQL Script generated by MySQL Workbench
-- Wed Sep 16 14:24:11 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema oficioive1722020
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `oficioive1722020` ;

-- -----------------------------------------------------
-- Schema oficioive1722020
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `oficioive1722020` DEFAULT CHARACTER SET utf8 ;
USE `oficioive1722020` ;

-- -----------------------------------------------------
-- Table `oficioive1722020`.`actuacionCliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oficioive1722020`.`actuacionCliente` ;

CREATE TABLE IF NOT EXISTS `oficioive1722020`.`actuacionCliente` (
  `idActuacionCliente` INT NOT NULL AUTO_INCREMENT,
  `tipoActuacion` VARCHAR(1) NOT NULL,
  `calidadActua` VARCHAR(100) NULL,
  `lugar` INT NOT NULL,
  `fecha` DATE NULL,
  `cliente` INT NOT NULL,
  PRIMARY KEY (`idActuacionCliente`),
  CONSTRAINT `fk_actclie_lugar`
    FOREIGN KEY (`lugar`)
    REFERENCES `oficioive1722020`.`lugar` (`idLugar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_actclie_lugar_idx` ON `oficioive1722020`.`actuacionCliente` (`lugar` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `oficioive1722020`.`departamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oficioive1722020`.`departamento` ;

CREATE TABLE IF NOT EXISTS `oficioive1722020`.`departamento` (
  `idDepartamento` INT NOT NULL AUTO_INCREMENT,
  `codigoDepartamento` VARCHAR(2) NOT NULL,
  `nombreDepartamento` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`idDepartamento`, `codigoDepartamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficioive1722020`.`lugar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oficioive1722020`.`lugar` ;

CREATE TABLE IF NOT EXISTS `oficioive1722020`.`lugar` (
  `idLugar` INT NOT NULL AUTO_INCREMENT,
  `pais` VARCHAR(2) NOT NULL,
  `departamento` VARCHAR(2) NULL,
  `municipio` VARCHAR(4) NULL,
  PRIMARY KEY (`idLugar`),
  CONSTRAINT `fk_lugar_pais`
    FOREIGN KEY (`pais`)
    REFERENCES `oficioive1722020`.`pais` (`codigoPais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lugar_departamento`
    FOREIGN KEY (`departamento`)
    REFERENCES `oficioive1722020`.`departamento` (`codigoDepartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lugar_municipio`
    FOREIGN KEY (`municipio`)
    REFERENCES `oficioive1722020`.`municipio` (`codigoMunicipio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_lugar_pais_idx` ON `oficioive1722020`.`lugar` (`pais` ASC) VISIBLE;

CREATE INDEX `fk_lugar_departamento_idx` ON `oficioive1722020`.`lugar` (`departamento` ASC) VISIBLE;

CREATE INDEX `fk_lugar_municipio_idx` ON `oficioive1722020`.`lugar` (`municipio` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `oficioive1722020`.`municipio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oficioive1722020`.`municipio` ;

CREATE TABLE IF NOT EXISTS `oficioive1722020`.`municipio` (
  `idmunicipio` INT NOT NULL AUTO_INCREMENT,
  `codigoDepartamento` VARCHAR(2) NOT NULL,
  `codigoMunicipio` VARCHAR(4) NOT NULL,
  `nombreMunicipio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idmunicipio`, `codigoMunicipio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficioive1722020`.`pais`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oficioive1722020`.`pais` ;

CREATE TABLE IF NOT EXISTS `oficioive1722020`.`pais` (
  `idPais` INT NOT NULL AUTO_INCREMENT,
  `codigoPais` VARCHAR(2) NOT NULL,
  `nombrePais` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPais`, `codigoPais`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `oficioive1722020`.`departamento`
-- -----------------------------------------------------
START TRANSACTION;
USE `oficioive1722020`;
INSERT INTO `oficioive1722020`.`departamento` (`idDepartamento`, `codigoDepartamento`, `nombreDepartamento`) VALUES (1, '01', 'GUATEMALA');
INSERT INTO `oficioive1722020`.`departamento` (`idDepartamento`, `codigoDepartamento`, `nombreDepartamento`) VALUES (2, '02', 'SACATEPÉQUEZ');
INSERT INTO `oficioive1722020`.`departamento` (`idDepartamento`, `codigoDepartamento`, `nombreDepartamento`) VALUES (3, '03', 'CHIMALTENANGO');
INSERT INTO `oficioive1722020`.`departamento` (`idDepartamento`, `codigoDepartamento`, `nombreDepartamento`) VALUES (4, '04', 'EL PROGRESO');
INSERT INTO `oficioive1722020`.`departamento` (`idDepartamento`, `codigoDepartamento`, `nombreDepartamento`) VALUES (5, '05', 'ESCUINTLA');
INSERT INTO `oficioive1722020`.`departamento` (`idDepartamento`, `codigoDepartamento`, `nombreDepartamento`) VALUES (6, '06', 'SANTA ROSA');
INSERT INTO `oficioive1722020`.`departamento` (`idDepartamento`, `codigoDepartamento`, `nombreDepartamento`) VALUES (7, '07', ' SOLOLÁ');
INSERT INTO `oficioive1722020`.`departamento` (`idDepartamento`, `codigoDepartamento`, `nombreDepartamento`) VALUES (8, '08', ' TOTONICAPÁN');
INSERT INTO `oficioive1722020`.`departamento` (`idDepartamento`, `codigoDepartamento`, `nombreDepartamento`) VALUES (9, '09', ' QUETZALTENANGO');
INSERT INTO `oficioive1722020`.`departamento` (`idDepartamento`, `codigoDepartamento`, `nombreDepartamento`) VALUES (10, '10', ' SUCHITEPÉQUEZ');
INSERT INTO `oficioive1722020`.`departamento` (`idDepartamento`, `codigoDepartamento`, `nombreDepartamento`) VALUES (11, '11', ' RETALHULEU');
INSERT INTO `oficioive1722020`.`departamento` (`idDepartamento`, `codigoDepartamento`, `nombreDepartamento`) VALUES (12, '12', ' SAN MARCOS');
INSERT INTO `oficioive1722020`.`departamento` (`idDepartamento`, `codigoDepartamento`, `nombreDepartamento`) VALUES (13, '13', ' HUEHUETENANGO');
INSERT INTO `oficioive1722020`.`departamento` (`idDepartamento`, `codigoDepartamento`, `nombreDepartamento`) VALUES (14, '14', ' EL QUICHÉ');
INSERT INTO `oficioive1722020`.`departamento` (`idDepartamento`, `codigoDepartamento`, `nombreDepartamento`) VALUES (15, '15', ' BAJA VERAPAZ');
INSERT INTO `oficioive1722020`.`departamento` (`idDepartamento`, `codigoDepartamento`, `nombreDepartamento`) VALUES (16, '16', ' ALTA VERAPAZ');
INSERT INTO `oficioive1722020`.`departamento` (`idDepartamento`, `codigoDepartamento`, `nombreDepartamento`) VALUES (17, '17', ' PETÉN');
INSERT INTO `oficioive1722020`.`departamento` (`idDepartamento`, `codigoDepartamento`, `nombreDepartamento`) VALUES (18, '18', ' IZABAL');
INSERT INTO `oficioive1722020`.`departamento` (`idDepartamento`, `codigoDepartamento`, `nombreDepartamento`) VALUES (19, '19', ' ZACAPA');
INSERT INTO `oficioive1722020`.`departamento` (`idDepartamento`, `codigoDepartamento`, `nombreDepartamento`) VALUES (20, '20', ' CHIQUIMULA');
INSERT INTO `oficioive1722020`.`departamento` (`idDepartamento`, `codigoDepartamento`, `nombreDepartamento`) VALUES (21, '21', ' JALAPA');
INSERT INTO `oficioive1722020`.`departamento` (`idDepartamento`, `codigoDepartamento`, `nombreDepartamento`) VALUES (22, '22', ' JUTIAPA');

COMMIT;

