-- MySQL Script generated by MySQL Workbench
-- Thu Sep 17 16:15:16 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema oficioive1722020
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `oficioive1722020` ;

-- -----------------------------------------------------
-- Schema oficioive1722020
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `oficioive1722020` DEFAULT CHARACTER SET utf8 ;
USE `oficioive1722020` ;

-- -----------------------------------------------------
-- Table `oficioive1722020`.`pais`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oficioive1722020`.`pais` ;

CREATE TABLE IF NOT EXISTS `oficioive1722020`.`pais` (
  `idPais` INT NOT NULL AUTO_INCREMENT,
  `codigoPais` VARCHAR(2) NOT NULL,
  `nombrePais` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPais`, `codigoPais`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficioive1722020`.`departamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oficioive1722020`.`departamento` ;

CREATE TABLE IF NOT EXISTS `oficioive1722020`.`departamento` (
  `idDepartamento` INT NOT NULL AUTO_INCREMENT,
  `codigoDepartamento` VARCHAR(2) NOT NULL,
  `nombreDepartamento` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`idDepartamento`, `codigoDepartamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficioive1722020`.`municipio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oficioive1722020`.`municipio` ;

CREATE TABLE IF NOT EXISTS `oficioive1722020`.`municipio` (
  `idmunicipio` INT NOT NULL AUTO_INCREMENT,
  `codigoDepartamento` VARCHAR(2) NOT NULL,
  `codigoMunicipio` VARCHAR(4) NOT NULL,
  `nombreMunicipio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idmunicipio`, `codigoMunicipio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficioive1722020`.`lugar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oficioive1722020`.`lugar` ;

CREATE TABLE IF NOT EXISTS `oficioive1722020`.`lugar` (
  `idLugar` INT NOT NULL AUTO_INCREMENT,
  `pais` VARCHAR(2) NOT NULL,
  `departamento` VARCHAR(2) NULL,
  `municipio` VARCHAR(4) NULL,
  PRIMARY KEY (`idLugar`),
  CONSTRAINT `fk_lugar_pais`
    FOREIGN KEY (`pais`)
    REFERENCES `oficioive1722020`.`pais` (`codigoPais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lugar_departamento`
    FOREIGN KEY (`departamento`)
    REFERENCES `oficioive1722020`.`departamento` (`codigoDepartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lugar_municipio`
    FOREIGN KEY (`municipio`)
    REFERENCES `oficioive1722020`.`municipio` (`codigoMunicipio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_lugar_pais_idx` ON `oficioive1722020`.`lugar` (`pais` ASC) VISIBLE;

CREATE INDEX `fk_lugar_departamento_idx` ON `oficioive1722020`.`lugar` (`departamento` ASC) VISIBLE;

CREATE INDEX `fk_lugar_municipio_idx` ON `oficioive1722020`.`lugar` (`municipio` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `oficioive1722020`.`listaCondicionMigratoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oficioive1722020`.`listaCondicionMigratoria` ;

CREATE TABLE IF NOT EXISTS `oficioive1722020`.`listaCondicionMigratoria` (
  `idlistaCondicionMigratoria` INT NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idlistaCondicionMigratoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficioive1722020`.`origenRiqueza`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oficioive1722020`.`origenRiqueza` ;

CREATE TABLE IF NOT EXISTS `oficioive1722020`.`origenRiqueza` (
  `idorigenRiqueza` INT NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idorigenRiqueza`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficioive1722020`.`datosPep`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oficioive1722020`.`datosPep` ;

CREATE TABLE IF NOT EXISTS `oficioive1722020`.`datosPep` (
  `idDatosPep` INT NOT NULL AUTO_INCREMENT,
  `entidad` VARCHAR(400) NOT NULL,
  `puestoDesempenia` VARCHAR(200) NOT NULL,
  `pais` VARCHAR(2) NOT NULL,
  `origenRiqueza` INT NOT NULL,
  `otroOrigenRiqueza` VARCHAR(100) NULL,
  PRIMARY KEY (`idDatosPep`),
  CONSTRAINT `fk_datospep_paisEntidad`
    FOREIGN KEY (`pais`)
    REFERENCES `oficioive1722020`.`pais` (`codigoPais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_datospep_origenRiqueza`
    FOREIGN KEY (`origenRiqueza`)
    REFERENCES `oficioive1722020`.`origenRiqueza` (`idorigenRiqueza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_paisEntidad_idx` ON `oficioive1722020`.`datosPep` (`pais` ASC) VISIBLE;

CREATE INDEX `fk_datospep_origenRiqueza_idx` ON `oficioive1722020`.`datosPep` (`origenRiqueza` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `oficioive1722020`.`parentescoPep`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oficioive1722020`.`parentescoPep` ;

CREATE TABLE IF NOT EXISTS `oficioive1722020`.`parentescoPep` (
  `idparentescoPep` INT NOT NULL AUTO_INCREMENT,
  `parentesco` VARCHAR(2) NOT NULL,
  `descripcionParentesco` VARCHAR(45) NULL,
  PRIMARY KEY (`idparentescoPep`, `parentesco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficioive1722020`.`motivoAsociacionPep`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oficioive1722020`.`motivoAsociacionPep` ;

CREATE TABLE IF NOT EXISTS `oficioive1722020`.`motivoAsociacionPep` (
  `idMotivoAsociacionPep` INT NOT NULL AUTO_INCREMENT,
  `motivoAsociacion` VARCHAR(2) NOT NULL,
  `descripcionMotivoAsociacion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMotivoAsociacionPep`, `motivoAsociacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficioive1722020`.`parienteAsociadoPep`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oficioive1722020`.`parienteAsociadoPep` ;

CREATE TABLE IF NOT EXISTS `oficioive1722020`.`parienteAsociadoPep` (
  `idparienteAsociadoPep` INT NOT NULL AUTO_INCREMENT,
  `parentesco` VARCHAR(2) NOT NULL,
  `otroParentesco` VARCHAR(100) NULL,
  `motivoAsociacion` VARCHAR(2) NOT NULL,
  `otroMotivoAsociacion` VARCHAR(100) NULL,
  `primerApellido` VARCHAR(15) NOT NULL,
  `segundoApellido` VARCHAR(15) NOT NULL,
  `apellidoCasada` VARCHAR(15) NULL,
  `primerNombre` VARCHAR(15) NOT NULL,
  `segundoNombre` VARCHAR(15) NOT NULL,
  `otrosNombres` VARCHAR(30) NULL,
  `sexo` VARCHAR(1) NOT NULL,
  `condificion` VARCHAR(1) NOT NULL,
  `entidad` VARCHAR(400) NOT NULL,
  `puestoDesempenia` VARCHAR(200) NOT NULL,
  `paisEntidad` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`idparienteAsociadoPep`),
  CONSTRAINT `fk_pap_ParentescoPep`
    FOREIGN KEY (`parentesco`)
    REFERENCES `oficioive1722020`.`parentescoPep` (`parentesco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pap_motivoAsociacionPep`
    FOREIGN KEY (`motivoAsociacion`)
    REFERENCES `oficioive1722020`.`motivoAsociacionPep` (`motivoAsociacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_paisEntidad_pais`
    FOREIGN KEY (`paisEntidad`)
    REFERENCES `oficioive1722020`.`pais` (`codigoPais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_parienteAsociadoPep_ParentescoPep_idx` ON `oficioive1722020`.`parienteAsociadoPep` (`parentesco` ASC) VISIBLE;

CREATE INDEX `fk_pap_motivoAsociacionPep_idx` ON `oficioive1722020`.`parienteAsociadoPep` (`motivoAsociacion` ASC) VISIBLE;

CREATE INDEX `fk_paisEntidad_pais_idx` ON `oficioive1722020`.`parienteAsociadoPep` (`paisEntidad` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `oficioive1722020`.`datosPersonales`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oficioive1722020`.`datosPersonales` ;

CREATE TABLE IF NOT EXISTS `oficioive1722020`.`datosPersonales` (
  `iddatosPersonales` INT NOT NULL AUTO_INCREMENT,
  `primerApellido` VARCHAR(15) NOT NULL,
  `segundoApellido` VARCHAR(15) NOT NULL,
  `apellidoCasada` VARCHAR(15) NULL,
  `primerNombre` VARCHAR(15) NOT NULL,
  `segundoNombre` VARCHAR(15) NOT NULL,
  `otrosNombres` VARCHAR(30) NULL,
  `fechaNacimiento` DATE NOT NULL,
  `nacionalidades` INT NOT NULL,
  `nacimiento` INT NOT NULL,
  `condicionMigratoria` INT NULL,
  `otraCondicionMigratoria` VARCHAR(100) NULL,
  `sexo` VARCHAR(1) NOT NULL,
  `estadoCivil` VARCHAR(1) NOT NULL,
  `profesionOficio` VARCHAR(100) NOT NULL,
  `tipoDocumentoIdentificacion` VARCHAR(1) NOT NULL,
  `numeroDocumentoIdentificacion` VARCHAR(20) NOT NULL,
  `emisionPasaporte` VARCHAR(2) NULL,
  `nit` VARCHAR(20) NOT NULL,
  `telefonos` INT NULL,
  `email` VARCHAR(100) NOT NULL,
  `direccionResidencia` VARCHAR(400) NOT NULL,
  `residencia` INT NULL,
  `pep` VARCHAR(1) NOT NULL,
  `datosPep` INT NULL,
  `parienteAsociadoPep` VARCHAR(1) NOT NULL,
  `datosParienteAsociadoPep` INT NULL,
  `cep` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`iddatosPersonales`),
  CONSTRAINT `fk_nacimiento_lugar`
    FOREIGN KEY (`nacimiento`)
    REFERENCES `oficioive1722020`.`lugar` (`idLugar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_condicionMigratoria_listaCondicionMigratoria`
    FOREIGN KEY (`condicionMigratoria`)
    REFERENCES `oficioive1722020`.`listaCondicionMigratoria` (`idlistaCondicionMigratoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_datosPep_datosPep`
    FOREIGN KEY (`datosPep`)
    REFERENCES `oficioive1722020`.`datosPep` (`idDatosPep`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_datospapep_parienteAsociadoPep`
    FOREIGN KEY (`datosParienteAsociadoPep`)
    REFERENCES `oficioive1722020`.`parienteAsociadoPep` (`idparienteAsociadoPep`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_residencia_lugar`
    FOREIGN KEY (`residencia`)
    REFERENCES `oficioive1722020`.`lugar` (`idLugar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_nacimiento_lugar_idx` ON `oficioive1722020`.`datosPersonales` (`nacimiento` ASC) VISIBLE;

CREATE INDEX `fk_condicionMigratoria_listaCondicionMigratoria_idx` ON `oficioive1722020`.`datosPersonales` (`condicionMigratoria` ASC) VISIBLE;

CREATE INDEX ` ` ON `oficioive1722020`.`datosPersonales` () VISIBLE;

CREATE INDEX `fk_pep_datosPep_idx` ON `oficioive1722020`.`datosPersonales` (`datosPep` ASC) VISIBLE;

CREATE INDEX `fk_datospapep_parienteAsociadoPep_idx` ON `oficioive1722020`.`datosPersonales` (`datosParienteAsociadoPep` ASC) VISIBLE;

CREATE INDEX `fk_residencia_lugar_idx` ON `oficioive1722020`.`datosPersonales` (`residencia` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `oficioive1722020`.`actuacionCliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oficioive1722020`.`actuacionCliente` ;

CREATE TABLE IF NOT EXISTS `oficioive1722020`.`actuacionCliente` (
  `idActuacionCliente` INT NOT NULL AUTO_INCREMENT,
  `tipoActuacion` VARCHAR(1) NOT NULL,
  `calidadActua` VARCHAR(100) NULL,
  `lugar` INT NOT NULL,
  `fecha` DATE NULL,
  `cliente` INT NOT NULL,
  `representante` INT NULL,
  PRIMARY KEY (`idActuacionCliente`),
  CONSTRAINT `fk_actclie_lugar`
    FOREIGN KEY (`lugar`)
    REFERENCES `oficioive1722020`.`lugar` (`idLugar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_actclie_cliente_datosPersonales`
    FOREIGN KEY (`cliente`)
    REFERENCES `oficioive1722020`.`datosPersonales` (`iddatosPersonales`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_actclie_representante_datosPersonales`
    FOREIGN KEY (`representante`)
    REFERENCES `oficioive1722020`.`datosPersonales` (`iddatosPersonales`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_actclie_lugar_idx` ON `oficioive1722020`.`actuacionCliente` (`lugar` ASC) VISIBLE;

CREATE INDEX `fk_actclie_cliente_datosPersonales_idx` ON `oficioive1722020`.`actuacionCliente` (`cliente` ASC) VISIBLE;

CREATE INDEX `fk_actclie_representante_datosPersonales_idx` ON `oficioive1722020`.`actuacionCliente` (`representante` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
